# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_clang_variantcling_v0.6:
        CONFIG: osx_64_clang_variantcling_v0.6
        UPLOAD_PACKAGES: 'True'
      osx_64_clang_variantdefault:
        CONFIG: osx_64_clang_variantdefault
        UPLOAD_PACKAGES: 'True'
      osx_64_clang_variantroot_20190625:
        CONFIG: osx_64_clang_variantroot_20190625
        UPLOAD_PACKAGES: 'True'
      osx_64_clang_variantroot_20191220:
        CONFIG: osx_64_clang_variantroot_20191220
        UPLOAD_PACKAGES: 'True'
      osx_64_clang_variantroot_20200518:
        CONFIG: osx_64_clang_variantroot_20200518
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)